-- MentorBridge Real Seed — CSE-B 2023 + 46 Real Faculty
-- Password for ALL accounts: amma

INSERT INTO users (name,email,password,role) VALUES
('Admin','admin@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','admin'),
('Dr. Sreevidya B.','sreevidya.b@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Peeta Basa Pati','peeta.basa.pati@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Amudha J.','amudha.j@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Deepa Gupta','deepa.gupta@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Supriya M.','supriya.m@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Suja P.','suja.p@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Beena B. M.','beena.b.m@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Manju Khanna','manju.khanna@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Tripty Singh','tripty.singh@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. B. Uma Maheswari','b.uma.maheswari@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Thangam S','thangam.s@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. S. Santhanalakshmi','s.santhanalakshmi@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Manju Venugopalan','manju.venugopalan@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Kumaran U.','kumaran.u@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Radha D.','radha.d@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Rimjhim Singh','rimjhim.singh@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Meena Belwal','meena.belwal@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. K Dinesh Kumar','k.dinesh.kumar@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Gurupriya M.','gurupriya.m@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Vishwas H. N.','vishwas.h.n@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Nalini Sampath','nalini.sampath@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Sreebha Bhaskaran','sreebha.bhaskaran@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Kavitha C. R.','kavitha.c.r@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Priyanka Vivek','priyanka.vivek@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Rajesh M.','rajesh.m@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Sangita Khare','sangita.khare@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Ullas S','ullas.s@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Nandu C. Nair','nandu.c.nair@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Nidhin Prabhakar T. V.','nidhin.prabhakar.t.v@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Sajitha Krishnan','sajitha.krishnan@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Daddala Yasoomkari','daddala.yasoomkari@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Sanghamitra Mishra','sanghamitra.mishra@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Amulyashree S','amulyashree.s@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Thushara G. A.','thushara.g.a@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Niharika Panda','niharika.panda@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Niranjan D K','niranjan.d.k@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Gayathri Ramasamy','gayathri.ramasamy@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Aiswariya Milan K.','aiswariya.milan.k@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Divya K V','divya.k.v@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Shinu M. R.','shinu.m.r@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Pooja Gowda','pooja.gowda@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('B Saranya Devi','b.saranya.devi@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Shalini Tiwari','shalini.tiwari@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Anjitha P','anjitha.p@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Dr. Reena Panwar','reena.panwar@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Neera Chaudhary','neera.chaudhary@amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','mentor'),
('Aditya Sanjay Pavale','bl.en.u4cse23101@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Ailuri Rahul Reddy','bl.en.u4cse23102@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Ananthajith A','bl.en.u4cse23103@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Annamraju Pranav Sathwik','bl.en.u4cse23104@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Akshat Govil','bl.en.u4cse23106@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Thammana Akshay','bl.en.u4cse23107@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Amogh Babi','bl.en.u4cse23108@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Amogh Misra','bl.en.u4cse23109@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Banda Vandhana','bl.en.u4cse23110@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Buruvu Sevanand Saketh Sai','bl.en.u4cse23111@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Bandari Amulya','bl.en.u4cse23112@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Chirra Ravindra Reddy','bl.en.u4cse23113@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Challa Vishwa Chaitanya Reddy','bl.en.u4cse23114@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Debapriya Kundu','bl.en.u4cse23115@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Dhrithi Juvva','bl.en.u4cse23116@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Dishita Dashora','bl.en.u4cse23117@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Dudyala Harikeerthan Reddy','bl.en.u4cse23118@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Dhanush P','bl.en.u4cse23120@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Dhruvika Koka','bl.en.u4cse23121@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Gangam Sai Samarth','bl.en.u4cse23122@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Geethika Yarabolu','bl.en.u4cse23123@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Ganavi S P','bl.en.u4cse23124@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Haren A','bl.en.u4cse23125@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Jammula Veera Venkata Sai Akshay','bl.en.u4cse23126@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Janhavi Harish Kulkarni','bl.en.u4cse23127@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Kadali Nikshita','bl.en.u4cse23128@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Kangati Shashidhar Reddy','bl.en.u4cse23129@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Kanukollu Lakshmi Anvitha','bl.en.u4cse23130@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Kolluru Sahithi','bl.en.u4cse23131@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('M Sai Meghana','bl.en.u4cse23132@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Maytrai Sharma','bl.en.u4cse23134@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Moneesh Kumar Pasumarthi','bl.en.u4cse23135@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Mukkara Sreeja','bl.en.u4cse23136@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Nagam Sudha Sravanthi','bl.en.u4cse23137@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Namburi Krishna Akshath Varma','bl.en.u4cse23138@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Nitesh N','bl.en.u4cse23139@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Patchala Haneesh','bl.en.u4cse23140@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Pola Pavitra Kumari','bl.en.u4cse23141@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Poripireddi Karthik','bl.en.u4cse23142@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Pranav Sharma K L','bl.en.u4cse23143@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Pranav Parimi','bl.en.u4cse23144@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Ranga Veera Manikanta Deekshith Munuganti','bl.en.u4cse23145@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Repalle Gnaneswar','bl.en.u4cse23146@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Reddi Tejeesh Sai','bl.en.u4cse23147@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Rochit Madamanchi','bl.en.u4cse23148@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('S Rushil','bl.en.u4cse23149@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('S Udhaya Sankari','bl.en.u4cse23150@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Sai Rithvik Ambati','bl.en.u4cse23151@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Saswat Subhankar','bl.en.u4cse23152@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Suhaag Aravind Pamali','bl.en.u4cse23153@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Saathwika B Parvathy','bl.en.u4cse23154@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Sudhan Shankar','bl.en.u4cse23155@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Taduri Abhichakra','bl.en.u4cse23157@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Tripurari Sameer Kumar Narasimha','bl.en.u4cse23158@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Uppala Krishna Kushal','bl.en.u4cse23159@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Veluru Venkata Varshith','bl.en.u4cse23160@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Santosh Kumar','bl.en.u4cse23161@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Rebba Venkata Skanda Vyvaswath','bl.en.u4cse23162@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Kanusu Manikanta Sai','bl.en.u4cse23163@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Sakkani Sushanth','bl.en.u4cse23164@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Ritu Solanki','bl.en.u4cse23165@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Langati Nikhil Reddy','bl.en.u4cse23166@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student'),
('Shaman K Vidyananda','bl.en.u4cse23167@bl.students.amrita.edu','$2y$10$ahbuPY1F4Plhx91ifJwsGeQq/Nw74oBi0YpdZfSvqrdhYy.4aETqa','student');

INSERT INTO mentor_profiles (user_id,specialization,department,quote,max_students,photo_url) VALUES
(2,'Assistant Professor (Sl. Gd.) / Vice Chairperson','Computer Science','Growth begins at the edge of your comfort zone.',20,'https://webfiles.amrita.edu/2014/01/JF2hTrM1-Ms-Sreevidya-B_faculty_amrita_university_Bengaluru_campus-1.jpg'),
(3,'Assistant Professor (Sr. Gd.) / Professor','Computer Science','Every question you ask is a step toward mastery.',20,'https://webfiles.amrita.edu/2024/02/njCkeQHE-peeta-basa-pati.jpg'),
(4,'Professor','Computer Science','Clarity of purpose drives excellence.',20,'https://webfiles.amrita.edu/2014/01/J0slKoqY-Dr-Amudha-J_faculty_amrita_university_Bengaluru_campus.jpg'),
(5,'Professor','Computer Science','Excellence is a journey, not a destination.',20,'https://webfiles.amrita.edu/2014/02/wJPatEK9-Dr-Deepa-Gupta_faculty_amrita_university_Bengaluru_campus.jpg'),
(6,'Professor','Computer Science','Let us unlock your potential together.',20,'https://webfiles.amrita.edu/2014/01/o0JDNVxK-supriya-m-begaluru-1.jpg'),
(7,'Professor','Computer Science','Discipline and dedication build success.',20,'https://webfiles.amrita.edu/2014/01/suja-p.jpg'),
(8,'Associate Professor','Computer Science','Learning is doing; growing is reflecting.',20,'https://webfiles.amrita.edu/2024/02/cvMLijkJ-beena-bm.jpg'),
(9,'Associate Professor','Computer Science','The best mentors listen first.',20,'https://webfiles.amrita.edu/2024/07/manju-khanna.jpg'),
(10,'Associate Professor','Computer Science','Challenges are opportunities in disguise.',20,'https://webfiles.amrita.edu/2025/01/tripty-computing-bengaluru.jpg'),
(11,'Associate Professor','Computer Science','Knowledge shared is knowledge multiplied.',20,'https://webfiles.amrita.edu/2025/05/uma-maheswari-faculty-amrita-university-bengaluru-campus.jpg'),
(12,'Associate Professor','Computer Science','Growth begins at the edge of your comfort zone.',20,'https://webfiles.amrita.edu/2024/02/ocTlIu8U-thangam-s.jpg'),
(13,'Assistant Professor (Sl. Gd.)','Computer Science','Every question you ask is a step toward mastery.',20,'https://webfiles.amrita.edu/2025/07/santhanalakshmii.jpg'),
(14,'Assistant Professor (Sl. Gd.)','Computer Science','Clarity of purpose drives excellence.',20,'https://webfiles.amrita.edu/2025/12/manju-computing-bng.jpg'),
(15,'Assistant Professor (Sl. Gd.)','Computer Science','Excellence is a journey, not a destination.',20,'https://webfiles.amrita.edu/2025/01/dr-kumaran-amrita-faculty-image.jpg'),
(16,'Assistant Professor (Sl. Gd.)','Computer Science','Let us unlock your potential together.',20,'https://webfiles.amrita.edu/2014/01/bP84fOcW-Radha-D_faculty_amrita_university_Bengaluru_campus.jpg'),
(17,'Assistant Professor (Sl. Gd.)','Computer Science','Discipline and dedication build success.',20,'https://webfiles.amrita.edu/2023/04/qsJXPnXK-rimjhim-singh-faculty.jpg'),
(18,'Assistant Professor (Sr. Gd.)','Computer Science','Learning is doing; growing is reflecting.',20,'https://webfiles.amrita.edu/2014/01/6cncrpBm-Ms-meena-belwal_faculty_amrita_university_Bengaluru_campus.jpg'),
(19,'Assistant Professor (Sr. Gd.)','Computer Science','The best mentors listen first.',20,'https://webfiles.amrita.edu/2025/07/k-dinesh-kumar.jpg'),
(20,'Assistant Professor (Sr. Gd.)','Computer Science','Challenges are opportunities in disguise.',20,'https://webfiles.amrita.edu/2024/02/uJmzjYoe-gurupriya.jpg'),
(21,'Assistant Professor (Sr. Gd.)','Computer Science','Knowledge shared is knowledge multiplied.',20,'https://webfiles.amrita.edu/2014/01/Z9eRlFX1-Mr-Vishwas-HN_faculty_amrita_university_Bengaluru_campus.jpg'),
(22,'Assistant Professor (Sr. Gd.)','Computer Science','Growth begins at the edge of your comfort zone.',20,'https://webfiles.amrita.edu/2014/01/Vf8LCMvb-Ms-Nalini-Sampath_faculty_amrita_university_Bengaluru_campus.jpg'),
(23,'Assistant Professor (Sr. Gd.)','Computer Science','Every question you ask is a step toward mastery.',20,'https://webfiles.amrita.edu/2014/01/cxb01Wdy-Ms-Sreebha-Bhaskaran_faculty_amrita_university_Bengaluru_campus.jpg'),
(24,'Assistant Professor (Sr. Gd.)','Computer Science','Clarity of purpose drives excellence.',20,'https://webfiles.amrita.edu/2014/01/0JSAHf3l-Ms-kavitha-Cr_faculty_amrita_university_Bengaluru_campus.jpg'),
(25,'Assistant Professor (Sr. Gd.)','Computer Science','Excellence is a journey, not a destination.',20,'https://webfiles.amrita.edu/2016/10/edc3kSFB-Ms-Priyanka-Vivek_faculty_amrita_university_Bengaluru_campus.jpg'),
(26,'Assistant Professor (Sr. Gd.) / Vice Chairperson','Computer Science','Let us unlock your potential together.',20,'https://webfiles.amrita.edu/2024/02/LP2UZtdp-rajesh.jpg'),
(27,'Assistant Professor (Sr. Gd.)','Computer Science','Discipline and dedication build success.',20,'https://webfiles.amrita.edu/2014/01/8r37i58C-Ms-Sangita-khare_faculty_amrita_university_Bengaluru_campus.jpg'),
(28,'Assistant Professor','Computer Science','Learning is doing; growing is reflecting.',20,'https://webfiles.amrita.edu/2014/01/qPpEgTxh-Ullas-S_faculty_amrita_university_Bengaluru_campus.jpg'),
(29,'Assistant Professor','Computer Science','The best mentors listen first.',20,'https://webfiles.amrita.edu/2025/07/nandu-c-nair.jpg'),
(30,'Assistant Professor','Computer Science','Challenges are opportunities in disguise.',20,'https://webfiles.amrita.edu/2024/02/hgWcQclc-nidhin-prabhakar-tv.jpg'),
(31,'Assistant Professor','Computer Science','Knowledge shared is knowledge multiplied.',20,'https://webfiles.amrita.edu/2024/02/LPcMhVNl-sajitha-krishnan.jpg'),
(32,'Assistant Professor','Computer Science','Growth begins at the edge of your comfort zone.',20,'https://webfiles.amrita.edu/2025/07/daddala-yasoomkari.jpg'),
(33,'Assistant Professor','Computer Science','Every question you ask is a step toward mastery.',20,'https://webfiles.amrita.edu/2025/07/sanghamitra-mishra.jpg'),
(34,'Assistant Professor','Computer Science','Clarity of purpose drives excellence.',20,'https://webfiles.amrita.edu/2025/07/amulyashree-s.jpg'),
(35,'Assistant Professor','Computer Science','Excellence is a journey, not a destination.',20,'https://webfiles.amrita.edu/2025/07/thushara-g-a.jpg'),
(36,'Assistant Professor','Computer Science','Let us unlock your potential together.',20,'https://webfiles.amrita.edu/2026/01/niharika-panda-asst-cse-blr.jpg'),
(37,'Assistant Professor (OC)','Computer Science','Discipline and dedication build success.',20,'https://webfiles.amrita.edu/2025/07/niranjan-d-k.jpg'),
(38,'Assistant Professor (OC)','Computer Science','Learning is doing; growing is reflecting.',20,'https://webfiles.amrita.edu/2024/02/X5hxaZTj-gayathri.jpg'),
(39,'Assistant Professor (OC)','Computer Science','The best mentors listen first.',20,'https://webfiles.amrita.edu/2024/07/aiswariya-milan-k.jpg'),
(40,'Assistant Professor (OC)','Computer Science','Challenges are opportunities in disguise.',20,'https://webfiles.amrita.edu/2024/07/divya-k-v-1.jpg'),
(41,'Assistant Professor (Sr. Gd.)','Computer Science','Knowledge shared is knowledge multiplied.',20,'https://webfiles.amrita.edu/2024/02/s0NgCMpy-shinu.jpg'),
(42,'Assistant Professor (OC)','Computer Science','Growth begins at the edge of your comfort zone.',20,'https://webfiles.amrita.edu/2025/07/pooja-gowda.jpg'),
(43,'Assistant Professor (OC)','Computer Science','Every question you ask is a step toward mastery.',20,'https://webfiles.amrita.edu/2025/07/b-saranya-devi.jpg'),
(44,'Assistant Professor (OC)','Computer Science','Clarity of purpose drives excellence.',20,'https://webfiles.amrita.edu/2025/12/shalini-asst-oc-computing-blr.jpg'),
(45,'Assistant Professor (OC)','Computer Science','Excellence is a journey, not a destination.',20,'https://webfiles.amrita.edu/2025/07/anjitha-p.jpg'),
(46,'Assistant Professor','Computer Science','Let us unlock your potential together.',20,'https://webfiles.amrita.edu/2025/07/reena-pawar-img.jpg'),
(47,'Assistant Professor (OC)','Computer Science','Discipline and dedication build success.',20,'https://webfiles.amrita.edu/2025/12/neera-chaudhary-assistant-professor-computing-bengaluru.jpg');

INSERT INTO student_profiles (user_id,department,roll_number) VALUES
(48,'Computer Science Engineering','BL.EN.U4CSE23101'),
(49,'Computer Science Engineering','BL.EN.U4CSE23102'),
(50,'Computer Science Engineering','BL.EN.U4CSE23103'),
(51,'Computer Science Engineering','BL.EN.U4CSE23104'),
(52,'Computer Science Engineering','BL.EN.U4CSE23106'),
(53,'Computer Science Engineering','BL.EN.U4CSE23107'),
(54,'Computer Science Engineering','BL.EN.U4CSE23108'),
(55,'Computer Science Engineering','BL.EN.U4CSE23109'),
(56,'Computer Science Engineering','BL.EN.U4CSE23110'),
(57,'Computer Science Engineering','BL.EN.U4CSE23111'),
(58,'Computer Science Engineering','BL.EN.U4CSE23112'),
(59,'Computer Science Engineering','BL.EN.U4CSE23113'),
(60,'Computer Science Engineering','BL.EN.U4CSE23114'),
(61,'Computer Science Engineering','BL.EN.U4CSE23115'),
(62,'Computer Science Engineering','BL.EN.U4CSE23116'),
(63,'Computer Science Engineering','BL.EN.U4CSE23117'),
(64,'Computer Science Engineering','BL.EN.U4CSE23118'),
(65,'Computer Science Engineering','BL.EN.U4CSE23120'),
(66,'Computer Science Engineering','BL.EN.U4CSE23121'),
(67,'Computer Science Engineering','BL.EN.U4CSE23122'),
(68,'Computer Science Engineering','BL.EN.U4CSE23123'),
(69,'Computer Science Engineering','BL.EN.U4CSE23124'),
(70,'Computer Science Engineering','BL.EN.U4CSE23125'),
(71,'Computer Science Engineering','BL.EN.U4CSE23126'),
(72,'Computer Science Engineering','BL.EN.U4CSE23127'),
(73,'Computer Science Engineering','BL.EN.U4CSE23128'),
(74,'Computer Science Engineering','BL.EN.U4CSE23129'),
(75,'Computer Science Engineering','BL.EN.U4CSE23130'),
(76,'Computer Science Engineering','BL.EN.U4CSE23131'),
(77,'Computer Science Engineering','BL.EN.U4CSE23132'),
(78,'Computer Science Engineering','BL.EN.U4CSE23134'),
(79,'Computer Science Engineering','BL.EN.U4CSE23135'),
(80,'Computer Science Engineering','BL.EN.U4CSE23136'),
(81,'Computer Science Engineering','BL.EN.U4CSE23137'),
(82,'Computer Science Engineering','BL.EN.U4CSE23138'),
(83,'Computer Science Engineering','BL.EN.U4CSE23139'),
(84,'Computer Science Engineering','BL.EN.U4CSE23140'),
(85,'Computer Science Engineering','BL.EN.U4CSE23141'),
(86,'Computer Science Engineering','BL.EN.U4CSE23142'),
(87,'Computer Science Engineering','BL.EN.U4CSE23143'),
(88,'Computer Science Engineering','BL.EN.U4CSE23144'),
(89,'Computer Science Engineering','BL.EN.U4CSE23145'),
(90,'Computer Science Engineering','BL.EN.U4CSE23146'),
(91,'Computer Science Engineering','BL.EN.U4CSE23147'),
(92,'Computer Science Engineering','BL.EN.U4CSE23148'),
(93,'Computer Science Engineering','BL.EN.U4CSE23149'),
(94,'Computer Science Engineering','BL.EN.U4CSE23150'),
(95,'Computer Science Engineering','BL.EN.U4CSE23151'),
(96,'Computer Science Engineering','BL.EN.U4CSE23152'),
(97,'Computer Science Engineering','BL.EN.U4CSE23153'),
(98,'Computer Science Engineering','BL.EN.U4CSE23154'),
(99,'Computer Science Engineering','BL.EN.U4CSE23155'),
(100,'Computer Science Engineering','BL.EN.U4CSE23157'),
(101,'Computer Science Engineering','BL.EN.U4CSE23158'),
(102,'Computer Science Engineering','BL.EN.U4CSE23159'),
(103,'Computer Science Engineering','BL.EN.U4CSE23160'),
(104,'Computer Science Engineering','BL.EN.U4CSE23161'),
(105,'Computer Science Engineering','BL.EN.U4CSE23162'),
(106,'Computer Science Engineering','BL.EN.U4CSE23163'),
(107,'Computer Science Engineering','BL.EN.U4CSE23164'),
(108,'Computer Science Engineering','BL.EN.U4CSE23165'),
(109,'Computer Science Engineering','BL.EN.U4CSE23166'),
(110,'Computer Science Engineering','BL.EN.U4CSE23167');

INSERT INTO semester_config (id,semester_name,goals_deadline,election_deadline)
VALUES (1,'Semester 2 - 2025-26','2026-08-31','2026-09-15')
ON DUPLICATE KEY UPDATE semester_name='Semester 2 - 2025-26',goals_deadline='2026-08-31',election_deadline='2026-09-15';
